# NOTE: run in the Claude session's own sandboxed Postgres instance (see
# Sprint 23-33's own test scripts for the full setup rationale — same
# auth_sim.sql approach, not this project's real local Supabase).
# Committed as a reproducible record of how Sprint 34's payroll claims
# were verified.
#
# Setup order for a fresh run: auth_sim.sql -> app/backend/schema.sql
# (current, already includes Sprint 23-33) -> GRANT ALL TABLES +
# SEQUENCES to authenticated -> this sprint's migration -> GRANT again
# (new tables/sequences) -> this script (does its own auth.users/
# businesses/Owner-membership seeding, same synthetic-domain approach
# every prior sprint's test script used).
#
# ============================================================
# NOTE ON STATUTORY RATES: EPF/SOCSO/EIS rates used here are real 2026
# published rates (researched via web search against secondary payroll-
# reference sources this session could reach — see the migration's own
# header note 3), NOT verified against LHDN/EPF/PERKESO's own primary
# tables directly. PCB is a SIMPLIFIED progressive-bracket
# approximation of the real PCB Schedule/Formula Method (see header
# note 4) — it does not model marital-status categories, children,
# zakat, or other reliefs. "Verified correct" below means: this
# script's own independently-computed reference (using the same
# published rates, computed by hand in Python, not copied from the SQL
# function) matches what compute_statutory_deductions actually
# returns — not that it matches LHDN's real PCB Schedule.
#
# NOTE ON BULK PAYMENT FILE: the CSV layout generated by
# generate_bulk_payment_file_export is a documented-generic Malaysian
# bulk-pay layout, per the owner's own explicit AskUserQuestion answer
# this sprint — NOT verified against Maybank2u's real portal template.
# DoD item 4 stays open in the Sprint 34 doc's Outcomes.
# ============================================================
#
# What this proves (Sprint 34 Definition of Done):
#   A. Statutory calculations verified correct (against this script's
#      own independent Python reference) for 3 salary levels: RM3,000
#      (below both EPF employer threshold and SOCSO/EIS ceiling),
#      RM6,500 (above EPF threshold, above SOCSO/EIS ceiling), and
#      RM12,000 (well above everything).
#   B. Payroll run approval hard-blocked from auto-approval — verified
#      two ways: (1) calling create_approval_task directly with
#      domain='payroll', auto_approved=true fails (Sprint 25/28's own
#      pre-existing guard); (2) submit_payroll_run's own approval task
#      is never resolved_via='auto_approved', proving no bypass
#      through this sprint's actual application code path.
#   C. e-payslip delivery marked end to end (channel + timestamp),
#      idempotency guard verified.
#   D. Bulk payment file generated (with the above caveat) and its CSV
#      structure verified (header row, 2-decimal amounts, one line per
#      employee).
#   E. Default role restriction on payroll domain verified by test: a
#      Sales Agent (no payroll grants at all, per Vol 13_1 §4.1's
#      seeded role_permissions) is denied view/capture on payroll.
#   Plus: Claim/SalaryAdvance approval-gating before being swept into
#   a run; encryption round-trip (correct key decrypts, wrong key
#   fails); ledger posting balances (debit == credit total).

import uuid
import psycopg2
import psycopg2.extras

DSN = "host=127.0.0.1 port=5432 dbname=aifa_sprint34_test user=postgres password=testpass123"

PAYROLL_ADMIN_ROLE = "00000000-0000-0000-0000-000000000005"
SALES_AGENT_ROLE = "00000000-0000-0000-0000-000000000003"

TEST_ENCRYPTION_KEY = "sprint34-throwaway-test-key-not-a-real-secret"


def u():
    return str(uuid.uuid4())


def as_user(cur, user_id):
    cur.execute("set role authenticated")
    cur.execute("select set_config('request.jwt.claim.sub', %s, false)", (user_id,))


def as_superuser(cur):
    cur.execute("reset role")


def check(label, actual, expected):
    status = "PASS" if actual == expected else f"FAIL (expected {expected!r}, got {actual!r})"
    print(f"[{status}] {label}")
    return actual == expected


def expect_error(label, cur, conn, fn):
    try:
        fn()
        print(f"[FAIL] {label} (no error raised)")
        return False
    except psycopg2.Error as e:
        print(f"[PASS] {label} ({str(e).strip().splitlines()[0]})")
        return True
    finally:
        conn.rollback()


def seed_business(cur, owner_email):
    owner_user = u()
    business_id = owner_user
    as_superuser(cur)
    cur.execute("insert into auth.users (id, email) values (%s, %s)", (owner_user, owner_email))
    cur.execute(
        "insert into public.businesses (id, owner_user_id, legal_name) values (%s, %s, %s)",
        (business_id, owner_user, owner_email),
    )
    cur.execute(
        "insert into public.business_memberships (business_id, user_id, role_id, status, invited_at, accepted_at) "
        "values (%s, %s, '00000000-0000-0000-0000-000000000001', 'active', now(), now()) returning id",
        (business_id, owner_user),
    )
    owner_membership_id = cur.fetchone()[0]
    return business_id, owner_user, owner_membership_id


def invite_and_accept(cur, conn, owner_user, business_id, role_id, email):
    as_user(cur, owner_user)
    cur.execute("select id from public.invite_member(%s, %s, %s)", (business_id, email, role_id))
    conn.commit()
    new_user = u()
    as_superuser(cur)
    cur.execute("insert into auth.users (id, email) values (%s, %s)", (new_user, email))
    conn.commit()
    as_user(cur, new_user)
    cur.execute("select id from public.accept_membership_invitation(%s)", (business_id,))
    membership_id = cur.fetchone()[0]
    conn.commit()
    return new_user, membership_id


# Independent Python reference for statutory deductions — NOT copied
# from the SQL function, computed fresh against the same published
# 2026 rates, to actually catch a discrepancy rather than confirm the
# SQL function agrees with itself.
def reference_statutory(gross):
    epf_employee = round(gross * 0.11, 2)
    epf_employer = round(gross * (0.13 if gross <= 5000 else 0.12), 2)
    socso_wage = min(gross, 6000)
    socso_employee = round(socso_wage * 0.005, 2)
    socso_employer = round(socso_wage * 0.0175, 2)
    eis_wage = min(gross, 6000)
    eis_employee = round(eis_wage * 0.002, 2)
    eis_employer = round(eis_wage * 0.002, 2)

    annual_gross = gross * 12
    epf_relief = min(epf_employee * 12, 7000)
    chargeable = max(annual_gross - epf_relief - 9000, 0)

    brackets = [
        (0, 5000, 0.00), (5000, 20000, 0.01), (20000, 35000, 0.03), (35000, 50000, 0.06),
        (50000, 70000, 0.11), (70000, 100000, 0.19), (100000, 400000, 0.25),
        (400000, 600000, 0.26), (600000, 2000000, 0.28), (2000000, None, 0.30),
    ]
    annual_tax = 0.0
    for lower, upper, rate in brackets:
        if chargeable > lower:
            taxable = min(chargeable, upper if upper is not None else chargeable) - lower
            annual_tax += taxable * rate
    pcb = round(annual_tax / 12, 2)

    return {
        "epf_employee": epf_employee, "epf_employer": epf_employer,
        "socso_employee": socso_employee, "socso_employer": socso_employer,
        "eis_employee": eis_employee, "eis_employer": eis_employer,
        "pcb_deduction": pcb,
    }


def main():
    conn = psycopg2.connect(DSN)
    conn.autocommit = False
    cur = conn.cursor()
    all_passed = True

    biz, owner, om_owner = seed_business(cur, "ownerZ@test.com")
    conn.commit()
    payroll_admin_user, om_payroll_admin = invite_and_accept(cur, conn, owner, biz, PAYROLL_ADMIN_ROLE, "paZ@test.com")
    sales_agent_user, om_sales_agent = invite_and_accept(cur, conn, owner, biz, SALES_AGENT_ROLE, "saZ@test.com")

    # ================= A: Statutory calculations, 3 salary levels =============
    for gross in (3000, 6500, 12000):
        as_superuser(cur)
        cur.execute(
            "select epf_employee, epf_employer, socso_employee, socso_employer, "
            "eis_employee, eis_employer, pcb_deduction "
            "from public.compute_statutory_deductions(%s, %s)",
            (gross, "2026-09-15"),
        )
        row = cur.fetchone()
        actual = {
            "epf_employee": float(row[0]), "epf_employer": float(row[1]),
            "socso_employee": float(row[2]), "socso_employer": float(row[3]),
            "eis_employee": float(row[4]), "eis_employer": float(row[5]),
            "pcb_deduction": float(row[6]),
        }
        expected = reference_statutory(gross)
        ok = actual == expected
        all_passed &= ok
        print(f"[{'PASS' if ok else 'FAIL'}] A: statutory deductions for RM{gross}/month match independent "
              f"Python reference — got {actual}, expected {expected}")

    # ------- fixtures: two employees --------------------------------------
    as_user(cur, payroll_admin_user)
    cur.execute(
        "select id from public.create_party(%s,'Amir Employee',null,%s,null,null,null,'+60161111111',null,null,null,0)",
        (biz, ["employee"]),
    )
    emp1_party_id = cur.fetchone()[0]
    cur.execute(
        "select id from public.create_party(%s,'Bala Employee',null,%s,null,null,null,'+60162222222',null,null,null,0)",
        (biz, ["employee"]),
    )
    emp2_party_id = cur.fetchone()[0]
    conn.commit()

    as_user(cur, sales_agent_user)
    all_passed &= expect_error(
        "Sales Agent (no payroll grants) cannot create an employee profile", cur, conn,
        lambda: cur.execute(
            "select public.create_employee_profile(%s,%s,'900101-01-1234',null,null,null,'Maybank','1234567890',"
            "3000,'full_time','2025-01-01',%s)",
            (biz, emp1_party_id, TEST_ENCRYPTION_KEY),
        ),
    )

    as_user(cur, payroll_admin_user)
    cur.execute(
        "select id from public.create_employee_profile(%s,%s,'900101-01-1234','EPF-001',null,null,'Maybank',"
        "'1234567890',3000,'full_time','2025-01-01',%s)",
        (biz, emp1_party_id, TEST_ENCRYPTION_KEY),
    )
    ep1_id = cur.fetchone()[0]
    cur.execute(
        "select id from public.create_employee_profile(%s,%s,'910202-02-5678','EPF-002',null,null,'CIMB',"
        "'9876543210',6500,'full_time','2025-01-01',%s)",
        (biz, emp2_party_id, TEST_ENCRYPTION_KEY),
    )
    ep2_id = cur.fetchone()[0]
    conn.commit()

    # Encryption round-trip: correct key decrypts, wrong key fails.
    as_user(cur, payroll_admin_user)
    cur.execute(
        "select ic_number, epf_number, bank_account_no from public.get_employee_profile_decrypted(%s,%s)",
        (ep1_id, TEST_ENCRYPTION_KEY),
    )
    ic, epf_no, bank_acc = cur.fetchone()
    conn.commit()
    ok = ic == "900101-01-1234" and epf_no == "EPF-001" and bank_acc == "1234567890"
    all_passed &= ok
    print(f"[{'PASS' if ok else 'FAIL'}] Encryption round-trip: correct key decrypts ic_number/epf_number/"
          f"bank_account_no back to their original values — got {(ic, epf_no, bank_acc)}")

    all_passed &= expect_error(
        "Encryption: the WRONG key fails to decrypt (not silently returns garbage)", cur, conn,
        lambda: cur.execute(
            "select ic_number from public.get_employee_profile_decrypted(%s,%s)", (ep1_id, "wrong-key-entirely"),
        ),
    )

    as_superuser(cur)
    cur.execute("select ic_number_encrypted from public.employee_profiles where id=%s", (ep1_id,))
    stored_bytes = cur.fetchone()[0]
    ok = b"900101" not in bytes(stored_bytes)
    all_passed &= ok
    print(f"[{'PASS' if ok else 'FAIL'}] Encryption: the raw stored column does NOT contain the plaintext IC number")

    as_user(cur, sales_agent_user)
    all_passed &= expect_error(
        "E: Sales Agent (no payroll grants at all) cannot view employee profiles", cur, conn,
        lambda: cur.execute(
            "select ic_number from public.get_employee_profile_decrypted(%s,%s)", (ep1_id, TEST_ENCRYPTION_KEY),
        ),
    )

    # ================= Claim / SalaryAdvance approval gating ==================
    as_user(cur, payroll_admin_user)
    cur.execute("select id, status from public.create_claim(%s,%s,150.00,'travel')", (biz, emp1_party_id))
    claim1_id, claim1_status = cur.fetchone()
    conn.commit()
    ok = claim1_status == "pending_approval"
    all_passed &= ok
    print(f"[{'PASS' if ok else 'FAIL'}] Claim starts as 'pending_approval'")

    cur.execute("select id from public.approval_tasks where subject_type='claim' and subject_id=%s", (claim1_id,))
    claim1_task_id = cur.fetchone()[0]
    as_user(cur, owner)
    cur.execute("select public.decide_approval_task(%s,'approved')", (claim1_task_id,))
    conn.commit()
    as_superuser(cur)
    cur.execute("select status from public.claims where id=%s", (claim1_id,))
    ok = cur.fetchone()[0] == "approved"
    all_passed &= ok
    print(f"[{'PASS' if ok else 'FAIL'}] Claim moves to 'approved' once its ApprovalTask is decided")

    as_user(cur, payroll_admin_user)
    cur.execute("select id, status, outstanding_balance from public.create_salary_advance(%s,%s,500.00)", (biz, emp2_party_id))
    adv1_id, adv1_status, adv1_balance = cur.fetchone()
    conn.commit()
    ok = adv1_status == "pending_approval" and float(adv1_balance) == 500.00
    all_passed &= ok
    print(f"[{'PASS' if ok else 'FAIL'}] SalaryAdvance starts 'pending_approval' with full outstanding_balance")

    cur.execute("select id from public.approval_tasks where subject_type='salary_advance' and subject_id=%s", (adv1_id,))
    adv1_task_id = cur.fetchone()[0]
    as_user(cur, owner)
    cur.execute("select public.decide_approval_task(%s,'approved')", (adv1_task_id,))
    conn.commit()

    # ================= B: PayrollRun — the hard auto-approval rule =============
    as_user(cur, payroll_admin_user)
    all_passed &= expect_error(
        "B: create_approval_task itself refuses domain='payroll' with auto_approved=true "
        "(Sprint 25/28's pre-existing guard, exercised directly)", cur, conn,
        lambda: cur.execute(
            "select public.create_approval_task(%s,'payroll','payroll_run',%s,1000.00,'forced auto-approve attempt',"
            "0.99,%s,true,null)",
            (biz, u(), om_payroll_admin),
        ),
    )

    as_user(cur, sales_agent_user)
    all_passed &= expect_error(
        "E: Sales Agent cannot create a payroll run (no capture on payroll)", cur, conn,
        lambda: cur.execute("select public.create_payroll_run(%s,'2026-09')", (biz,)),
    )

    as_user(cur, payroll_admin_user)
    cur.execute("select id, total_net_pay from public.create_payroll_run(%s,'2026-09')", (biz,))
    run_id, total_net_pay = cur.fetchone()
    conn.commit()

    cur.execute(
        "select employee_party_id, gross_pay, epf_employee, socso_employee, eis_employee, pcb_deduction, "
        "claims_included, advance_deducted, net_pay from public.payslips where payroll_run_id=%s order by gross_pay",
        (run_id,),
    )
    payslip_rows = {r[0]: r for r in cur.fetchall()}
    conn.commit()

    ps1 = payslip_rows[emp1_party_id]
    exp1 = reference_statutory(3000.0)
    expected_net1 = 3000.0 - exp1["epf_employee"] - exp1["socso_employee"] - exp1["eis_employee"] \
        - exp1["pcb_deduction"] + 150.00 - 0.00
    ok = float(ps1[6]) == 150.00 and float(ps1[7]) == 0.00 and round(float(ps1[8]), 2) == round(expected_net1, 2)
    all_passed &= ok
    print(f"[{'PASS' if ok else 'FAIL'}] Employee 1's payslip includes the approved RM150 claim, no advance, "
          f"net_pay={ps1[8]} matches hand-computed {expected_net1:.2f}")

    ps2 = payslip_rows[emp2_party_id]
    exp2 = reference_statutory(6500.0)
    expected_net2 = 6500.0 - exp2["epf_employee"] - exp2["socso_employee"] - exp2["eis_employee"] \
        - exp2["pcb_deduction"] + 0.00 - 500.00
    ok = float(ps2[6]) == 0.00 and float(ps2[7]) == 500.00 and round(float(ps2[8]), 2) == round(expected_net2, 2)
    all_passed &= ok
    print(f"[{'PASS' if ok else 'FAIL'}] Employee 2's payslip deducts the full RM500 approved advance, "
          f"net_pay={ps2[8]} matches hand-computed {expected_net2:.2f}")

    as_superuser(cur)
    cur.execute("select status from public.claims where id=%s", (claim1_id,))
    ok = cur.fetchone()[0] == "included_in_payroll"
    all_passed &= ok
    print(f"[{'PASS' if ok else 'FAIL'}] Claim flips to 'included_in_payroll' once swept into the run")

    cur.execute("select status, outstanding_balance from public.salary_advances where id=%s", (adv1_id,))
    adv_status, adv_balance = cur.fetchone()
    ok = adv_status == "fully_deducted" and float(adv_balance) == 0.00
    all_passed &= ok
    print(f"[{'PASS' if ok else 'FAIL'}] SalaryAdvance flips to 'fully_deducted', outstanding_balance zeroed")

    as_user(cur, payroll_admin_user)
    cur.execute("select status from public.submit_payroll_run(%s)", (run_id,))
    submitted_status = cur.fetchone()[0]
    conn.commit()
    ok = submitted_status == "pending_approval"
    all_passed &= ok
    print(f"[{'PASS' if ok else 'FAIL'}] submit_payroll_run moves status to 'pending_approval'")

    as_superuser(cur)
    cur.execute(
        "select resolved_via, status from public.approval_tasks where subject_type='payroll_run' and subject_id=%s",
        (run_id,),
    )
    resolved_via, task_status = cur.fetchone()
    ok = resolved_via != "auto_approved" and task_status == "pending_approval"
    all_passed &= ok
    print(f"[{'PASS' if ok else 'FAIL'}] B: submit_payroll_run's own ApprovalTask was NOT auto_approved "
          f"(resolved_via={resolved_via!r}, status={task_status!r}) — no bypass through the real application path")

    cur.execute(
        "select id from public.approval_tasks where subject_type='payroll_run' and subject_id=%s order by created_at desc limit 1",
        (run_id,),
    )
    run_task_id = cur.fetchone()[0]
    as_user(cur, owner)
    cur.execute("select public.decide_approval_task(%s,'approved')", (run_task_id,))
    conn.commit()

    as_superuser(cur)
    cur.execute("select status from public.payroll_runs where id=%s", (run_id,))
    ok = cur.fetchone()[0] == "approved"
    all_passed &= ok
    print(f"[{'PASS' if ok else 'FAIL'}] PayrollRun flips to 'approved' once its ApprovalTask is decided")

    # ================= C: e-payslip delivery ===================================
    as_superuser(cur)
    cur.execute("select id from public.payslips where payroll_run_id=%s and employee_party_id=%s", (run_id, emp1_party_id))
    ps1_id = cur.fetchone()[0]

    as_user(cur, payroll_admin_user)
    cur.execute("select e_payslip_sent_at, e_payslip_channel from public.mark_payslip_sent(%s,'whatsapp')", (ps1_id,))
    sent_at, channel = cur.fetchone()
    conn.commit()
    ok = sent_at is not None and channel == "whatsapp"
    all_passed &= ok
    print(f"[{'PASS' if ok else 'FAIL'}] C: mark_payslip_sent records channel='whatsapp' and a delivery timestamp")

    all_passed &= expect_error(
        "C: mark_payslip_sent refused on an already-sent payslip (idempotency guard)", cur, conn,
        lambda: cur.execute("select public.mark_payslip_sent(%s,'email')", (ps1_id,)),
    )

    # ================= D: Bulk payment file export =============================
    as_user(cur, sales_agent_user)
    all_passed &= expect_error(
        "D: Sales Agent cannot generate the bulk payment file", cur, conn,
        lambda: cur.execute(
            "select public.generate_bulk_payment_file_export(%s,%s)", (run_id, TEST_ENCRYPTION_KEY),
        ),
    )

    as_user(cur, payroll_admin_user)
    cur.execute(
        "select bank_format, file_content from public.generate_bulk_payment_file_export(%s,%s)",
        (run_id, TEST_ENCRYPTION_KEY),
    )
    bank_format, file_content = cur.fetchone()
    conn.commit()
    lines = [l for l in file_content.strip().split("\n") if l]
    ok = (
        bank_format == "Maybank2u"
        and lines[0] == "Recipient Name,Recipient Bank Name,Recipient Bank Account No,Amount,Payment Reference,Payment Date"
        and len(lines) == 3  # header + 2 employees
        and "1234567890" in file_content
        and "9876543210" in file_content
    )
    all_passed &= ok
    print(f"[{'PASS' if ok else 'FAIL'}] D: bulk payment file CSV has the expected header, one line per employee, "
          f"and both real (decrypted) bank account numbers — got {len(lines)} lines")
    print("     NOTE: this CSV layout is NOT verified against Maybank2u's real portal template — see the "
          "migration's own owner-decision header and the Sprint 34 doc Outcomes. DoD item 4 stays open.")

    all_passed &= expect_error(
        "D: a second bulk payment file for the same already-exported run is rejected", cur, conn,
        lambda: cur.execute(
            "select public.generate_bulk_payment_file_export(%s,%s)", (run_id, TEST_ENCRYPTION_KEY),
        ),
    )

    # ================= mark_payroll_run_paid — ledger posting ==================
    as_user(cur, payroll_admin_user)
    cur.execute("select status from public.mark_payroll_run_paid(%s)", (run_id,))
    paid_status = cur.fetchone()[0]
    conn.commit()
    ok = paid_status == "paid"
    all_passed &= ok
    print(f"[{'PASS' if ok else 'FAIL'}] mark_payroll_run_paid moves PayrollRun to 'paid'")

    as_superuser(cur)
    cur.execute(
        "select coalesce(sum(case when direction='debit' then amount else 0 end),0), "
        "coalesce(sum(case when direction='credit' then amount else 0 end),0) "
        "from public.ledger_entries le join public.chart_of_accounts coa on coa.id=le.chart_of_accounts_id "
        "where coa.account_code in ('6500','2100','1000') and le.business_id=%s",
        (biz,),
    )
    debit_total, credit_total = cur.fetchone()
    ok = round(float(debit_total), 2) == round(float(credit_total), 2) and float(debit_total) > 0
    all_passed &= ok
    print(f"[{'PASS' if ok else 'FAIL'}] Payroll ledger posting balances: debit total {debit_total} == "
          f"credit total {credit_total}")

    print()
    print("ALL PASSED" if all_passed else "SOME FAILED")
    print()
    print("REMINDER: PCB is a simplified progressive-bracket approximation, not LHDN's literal PCB")
    print("Schedule/Formula Method; the bulk payment file CSV layout is not verified against")
    print("Maybank2u's real portal template. See the migration's own header and the Sprint 34")
    print("doc's Outcomes for what stays explicitly open.")
    conn.close()
    return 0 if all_passed else 1


if __name__ == "__main__":
    import sys
    sys.exit(main())
